'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from './header/header'
import './layout.css';

import { UpdateTitle } from './lib/store';
import { use } from 'react'
import { Button } from './Button/Button';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { title, subTitle } = UpdateTitle();
  return (
    <html>
     <body > 
     <Header /> {/* Must be inside body */}
      <div className="page-layout">
    <div className="page-title">
        <div className="page-heading">{title}</div>
        {/* <div className="page-subheading">{subTitle}</div> */}
        {subTitle !=='' && (<Button type="tertiary" value={subTitle} click={false} disabled={false} ></Button>)}

    </div>
    <div className="page-content">
        {children}
    </div>
    </div>
    </body>
    </html>
  )
}
